//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractParties = new HashSet<ContractParties>();
            this.Debt = new HashSet<Debt>();
        }
    
        public int ContractId { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime EndingDate { get; set; }
        public string Tenancy { get; set; }
        public string Neighborhood { get; set; }
        public string Street { get; set; }
        public string Apartment { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public string RealtyType { get; set; }
        public string RentMoneyInMonth { get; set; }
        public string RentMoneyTotal { get; set; }
        public string PaymentType { get; set; }
        public string PaymentDay { get; set; }
        public string CurrentSituationOfRealEstate { get; set; }
        public string AimOfRent { get; set; }
        public string InventoryList { get; set; }
        public string ContractSpecialConditions { get; set; }
        public string LandlordCitizenshipId { get; set; }
        public string LandlordFullName { get; set; }
        public string LandlordPhone { get; set; }
        public string LandlordAddress { get; set; }
        public string LandlordBankAccountName { get; set; }
        public string LandlordBankAccountNumber { get; set; }
        public string LandlordIBAN { get; set; }
        public string Explanation { get; set; }
        public int FileNumber { get; set; }
        public string RealtyDefinition { get; set; }
        public System.DateTime CancellationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractParties> ContractParties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Debt> Debt { get; set; }
    }
}
