//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Debt()
        {
            this.CashBook = new HashSet<CashBook>();
        }
    
        public int DebtId { get; set; }
        public string Definition { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DueDate { get; set; }
        public string PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public bool IsPaidByTenant { get; set; }
        public string Explanation { get; set; }
        public int ContractId { get; set; }
        public bool IsPaidToLandlord { get; set; }
        public bool IsCommission { get; set; }
        public string PaymentDateToLandlord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBook> CashBook { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
