//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realty
    {
        public int RealtyId { get; set; }
        public string Definition { get; set; }
        public Nullable<int> RealtyTypeId { get; set; }
        public string Neighborhood { get; set; }
        public string Street { get; set; }
        public string Apartment { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string Explanation { get; set; }
    
        public virtual RealtyType RealtyType { get; set; }
    }
}
